version: "3"
services:
  web:
    image: chashaotm/mychain:latest
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "3000:3000"
      - "5000:5000"
    networks:
      - webnet
  discovery:
    image: chashaotm/mychain:discovery
    ports:
      - "30000:30000"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
     - webnet
networks:
  webnet: